apiVersion: mirror.fluxcd.io/v1alpha1
kind: Config
artifacts:
  - source: ghcr.io/grimmory-tools/grimmory
    destination: ghcr.io/jdavid77/grimmory
    selector:
      semver: ">= 3.0.0"
      limit: 5
    includeReferrers: true
  - source: ghcr.io/rendercv/rendercv
    destination: ghcr.io/jdavid77/rendercv
    selector:
      semver: ">= 2.0.0"
      limit: 5
    includeReferrers: true
  - source: ghcr.io/calibrain/shelfmark
    destination: ghcr.io/jdavid77/shelfmark
    selector:
      semver: ">= 1.0.0"
      limit: 5
    includeReferrers: true
  - source: ghcr.io/seanmorley15/adventurelog-backend
    destination: ghcr.io/jdavid77/adventurelog-backend
    selector:
      semver: ">= 0.0.0"
      limit: 5
    includeReferrers: true
  - source: ghcr.io/seanmorley15/adventurelog-frontend
    destination: ghcr.io/jdavid77/adventurelog-frontend
    selector:
      semver: ">= 0.0.0"
      limit: 5
    includeReferrers: true
